tap "derailed/k9s"
tap "homebrew/bundle"
tap "homebrew/cask-fonts", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask-fonts.git"
#tap "lencx/chatgpt", "https://github.com/lencx/ChatGPT.git"
tap "homebrew/cask-versions", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask-versions.git"
tap "homebrew/command-not-found", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-command-not-found.git"
tap "homebrew/services", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-services.git"
tap "universal-ctags/universal-ctags"
cask "alacritty"
cask "emacs"
cask "font-hack-nerd-font"
cask "hammerspoon"
cask "kawa"
cask "mos"
cask "openlens"
cask "postman"
cask "vagrant"
cask "zap"

brew "derailed/k9s/k9s"

brew "git"
brew "git-delta"
brew "exa"
brew "stow"
brew "zoxide"
brew "lazygit"
brew "neovim"
brew "ripgrep"
brew "fzf"
brew "ffmpeg"
brew "zsh"
brew "tmux"
brew "tmuxinator"
brew "bat"
brew "wget"

brew "gobject-introspection"
brew "google-java-format"
brew "universal-ctags"
brew "maven"
brew "cmake"
brew "conan"brew "k9s"
brew "kind"
brew "kubernetes-cli"
brew "krew"
brew "kustomize"
brew "helm"
brew "minikube"

vscode "eamodio.gitlens"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "hoovercj.vscode-settings-cycler"
vscode "James-Yu.latex-workshop"
vscode "jeff-hykin.better-dockerfile-syntax"
vscode "LeetCode.vscode-leetcode"
vscode "marquesmps.dockerfile-validator"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode.makefile-tools"
vscode "redhat.java"
vscode "VisualStudioExptTeam.intellicode-api-usage-examples"
vscode "VisualStudioExptTeam.vscodeintellicode"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscodevim.vim"


brew "jpeg-xl"
brew "aom"
brew "argocd"
brew "aws-nuke"
brew "awscli"
brew "glib"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "pango"
brew "tesseract"
brew "gdk-pixbuf"
brew "gh"
brew "global"
brew "glow"
brew "librsvg"
brew "graphviz"
brew "guile"
brew "iperf3"
brew "jq"
brew "llvm"
brew "mercurial"
brew "nghttp2"
brew "qemu"
brew "ranger"
brew "reattach-to-user-namespace"
brew "telnet"
brew "terraform"
brew "tree"
brew "yarn"

