#!/bin/sh
[ -f "$HOME/.local/share/zap/zap.zsh" ] && source "$HOME/.local/share/zap/zap.zsh"


# history
HISTFILE=~/.zsh_history

# source
plug "$HOME/.config/zsh/exports.zsh"
plug "$HOME/.config/zsh/cli.zsh"
plug "$HOME/.config/zsh/function.zsh"
plug "$HOME/.config/zsh/eval.zsh"
plug "$HOME/.config/zsh/kube.zsh"
plug "$HOME/.config/zsh/aliases.zsh"

# plugins
plug "esc/conda-zsh-completion"
plug "zsh-users/zsh-autosuggestions"
# plug "hlissner/zsh-autopair"
plug "zap-zsh/supercharge"
plug "zap-zsh/vim"
# plug "spaceship-prompt/spaceship-prompt"
# plug "zap-zsh/atmachine-prompt"
plug "zap-zsh/zap-prompt"
plug "zap-zsh/fzf"
# plug "zap-zsh/exa"
plug "zsh-users/zsh-syntax-highlighting"
#
# eval "$(starship init zsh)"

# n Zsh, the no_nomatch option is used to control how the shell handles glob patterns that do not match any files.
# By default, Zsh will generate an error if a glob pattern does not match any files,
# displaying a message like zsh: no matches found: pattern. #
# This behavior can be problematic in scripts or commands where unmatched patterns are acceptable or expected.
setopt no_nomatch


# plug "spaceship-prompt/spaceship-prompt"

UNAME_MACHINE="$(/usr/bin/uname -m)"

if [[ "${UNAME_MACHINE}" == "arm64" ]]
then
  # On ARM macOS, this script installs to /opt/homebrew only
  HOMEBREW_PREFIX="/opt/homebrew"
  HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}"
else
  # On Intel macOS, this script installs to /usr/local only
  HOMEBREW_PREFIX="/usr/local"
  HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}/Homebrew"
fi


# keybinds
bindkey '^ ' autosuggest-accept



[ -f "/Users/samhuang/.ghcup/env" ] && . "/Users/samhuang/.ghcup/env" # ghcup-env



[[ "$TERM_PROGRAM" == "kiro" ]] && . "$(kiro --locate-shell-integration-path zsh)"



source /Users/samhuang/.config/broot/launcher/bash/br

export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"

