approvals_reviewer = "user"
[projects."/private/tmp"]
trust_level = "trusted"

[projects."/private/tmp/pr"]
trust_level = "trusted"

[projects."/private/tmp/todo"]
trust_level = "trusted"

[projects."/Users/samhuang/git/zilliz-cloud-mgmt"]
trust_level = "trusted"

[projects."/Users/samhuang/.config/opencode"]
trust_level = "trusted"

[projects."/Users/samhuang/git/zilliz-cloud"]
trust_level = "trusted"

[projects."/Users/samhuang/git/terraform-provider-zillizcloud"]
trust_level = "trusted"

[projects."/Users/samhuang/git"]
trust_level = "trusted"

[projects."/Users/samhuang/Downloads/untitled folder"]
trust_level = "trusted"

[projects."/Users/samhuang/git/vdc-deploy-prod"]
trust_level = "trusted"

[projects."/Users/samhuang/.config/nvim"]
trust_level = "trusted"

[projects."/Users/samhuang/git/sandbox/vpc-peering2"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4
[features]
goals = true

[marketplaces.cloud-skills]
last_updated = "2026-05-17T12:09:34Z"
last_revision = "af79d35db74ff2b8273a9a02e95b6ee7d3abd125"
source_type = "git"
source = "https://github.com/zilliztech/cloud-skills.git"

[marketplaces.openai-bundled]
last_updated = "2026-05-17T09:12:39Z"
source_type = "local"
source = "/Users/samhuang/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-08T09:30:33Z"
source_type = "local"
source = "/Users/samhuang/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins]
[plugins."sre-toolkit@cloud-skills"]
enabled = false

[plugins."ecc@ecc"]
enabled = false

[plugins."browser-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true
