k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: true
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: true
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: k8s-us1
  currentCluster: arn:aws:eks:us-west-2:670409000460:cluster/k8s-us1
  clusters:
    4am-kubernetes:
      namespace:
        active: milvus-ci
        lockFavorites: false
        favorites:
        - monitoring
        - ci-jenkins
        - all
        - milvus-ci
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:us-west-2:306787409409:cluster/sit-vdc-test:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:us-west-2:670409000460:cluster/k8s-us1:
      namespace:
        active: towhee
        lockFavorites: false
        favorites:
        - towhee
        - prow
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    ci-kubernetes:
      namespace:
        active: jenkins
        lockFavorites: false
        favorites:
        - monitoring
        - milvus-ci
        - kube-storage
        - knowhere-ci
        - all
        - jenkins
        - default
      view:
        active: pod
      featureGates:
        nodeShell: true
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    ci-sh-kubernetes:
      namespace:
        active: knowhere-ci
        lockFavorites: false
        favorites:
        - kube-storage
        - knowhere-ci
        - all
        - jenkins
        - default
      view:
        active: pods
      featureGates:
        nodeShell: true
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    minikube:
      namespace:
        active: jenkins
        lockFavorites: false
        favorites:
        - all
        - monitoring
        - jenkins
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/q9/06c1_qkx5dvfbz5wvdbxg4h00000gn/T/k9s-screens-zilliz
